{{- if .Values.tlsInternal.enabled }}
{{ include "governor.cert-manager.certificate" (dict
  "root" .
  "name" (printf "%s-cert" .Values.api.name)
  "app" .Values.api.name
  "secretName" (printf "%s-tls" .Values.api.name)
  "cert" .Values.tlsInternal.certificates
  "certificate" .Values.api.tlsInternal.certificate
  "defaultDnsName" (printf "%s.%s.svc.cluster.local" .Values.api.name .Release.Namespace)
) }}
{{- end }}
