{{- $w := include "governor.workerValues" . | fromYaml -}}
{{- if .Values.tlsInternal.enabled }}
{{ include "governor.cert-manager.certificate" (dict
  "root" .
  "name" (printf "%s-cert" $w.name)
  "app" $w.name
  "secretName" (printf "%s-tls" $w.name)
  "cert" .Values.tlsInternal.certificates
  "certificate" $w.tlsInternal.certificate
  "defaultDnsName" (printf "%s.%s.svc.cluster.local" $w.name .Release.Namespace)
) }}
{{- end }}
