resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

databases:
  - name: api-backend
    image:
      repository: postgres
      tag: "15"
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 5432
    secret:
      postgresUser: backend_user
      postgresPassword: "backend_password"
    persistence:
      accessMode: ReadWriteOnce
      size: 1Gi
  - name: input-source
    image:
      repository: synthesizedio/pagila
      tag: "1.8"
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 5432
    secret:
      postgresUser: postgres
      postgresPassword: "input_source"
    persistence:
      accessMode: ReadWriteOnce
      size: 10Gi
  - name: custom-source
    image:
      repository: postgres
      tag: "15"
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 5432
    secret:
      postgresUser: custom-source
      postgresPassword: "custom-source"
    persistence:
      accessMode: ReadWriteOnce
      size: 10Gi
  - name: output-source
    image:
      repository: postgres
      tag: "15"
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 5432
    secret:
      postgresUser: output_source
      postgresPassword: "output_source"
    persistence:
      accessMode: ReadWriteOnce
      size: 10Gi
