{{- if .Values.aurora.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.aurora.secretName }}
type: Opaque
stringData:
  {{ .Values.aurora.secretKey }}: {{ randAlphaNum 20 | quote }}
---
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBCluster
metadata:
  name: {{ .Release.Name }}-aurora-cluster
spec:
  dbClusterIdentifier: tenant-{{ .Release.Name }}-aurora-cluster
  engine: aurora-postgresql
  engineVersion: "13.6"
  masterUsername: {{ .Values.aurora.masterUsername | quote }}
  masterUserPassword:
    name: {{ .Values.aurora.secretName | quote }}
    key: {{ .Values.aurora.secretKey | quote }}
  dbSubnetGroupName: {{ .Values.aurora.dbSubnetGroupName | quote }}
  vpcSecurityGroupIDs:
  {{- range .Values.aurora.securityGroupIds }}
    - {{ . | quote }}
  {{- end }}
  backupRetentionPeriod: {{ .Values.aurora.backupRetentionPeriod }}
---
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBInstance
metadata:
  name: {{ .Release.Name }}-aurora-instance
spec:
  dbInstanceIdentifier: tenant-{{ .Release.Name }}-aurora-instance
  dbInstanceClass: {{ .Values.aurora.instanceClass | quote }}
  dbClusterIdentifier: tenant-{{ .Release.Name }}-aurora-cluster
  engine: aurora-postgresql
{{- end }}
