apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.api.name }}-configmap
data:
{{- if .Values.api.container.config }}
{{ toYaml .Values.api.container.config | indent 2}}
{{- end }}
{{- if eq .Values.mode "saas" }}
  DIRECTOR_SERVERHOST: "{{ .Values.director.name }}"
  DIRECTOR_SERVERPORT: "{{ .Values.director.service.port }}"
  GOVERNOR_SECURITY_OWNERACCESSONLY: "yes"
{{- end }}
