{{- $secretName := printf "%s-credentials" .Release.Name }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- $jwt := default "" .Values.api.container.secretConfig.JWT_SECRET }}
{{- if not $jwt }}
  {{- if and $existing $existing.data }}
    {{- $jwt = index $existing.data "jwt" | b64dec }}
  {{- else }}
    {{- $jwt = randAlphaNum 256 }}
  {{- end }}
{{- end }}
{{- $admin := default "" .Values.api.container.secretConfig.ADMIN_DEFAULT_PASSWORD }}
{{- if not $admin }}
  {{- if and $existing $existing.data }}
    {{- $admin = index $existing.data "admin" | b64dec }}
  {{- else }}
    {{- $admin = randAlphaNum 16 }}
  {{- end }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.api.name }}-secret
type: Opaque
data:
{{- range $k, $v := .Values.api.container.secretConfig }}
  {{ $k }}: {{ $v | b64enc | quote }}
  {{- end }}
  JWT_SECRET: {{ b64enc $jwt | quote }}
  ADMIN_DEFAULT_PASSWORD: {{ b64enc $admin | quote }}
