apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}-grpc
  labels:
    group: {{ .Values.api.group }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app: {{ .Values.api.name }}
  ports:
    - port: {{ .Values.api.service.grpcPort }}
      targetPort: {{ .Values.api.container.grpcPort }}
