apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}-grpc
  labels:
    group: {{ .Values.api.group }}
  annotations:
{{- range $key, $value := .Values.api.service.grpcAnnotations }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
    
spec:
  type: {{ .Values.api.service.grpcType }}
  selector:
    app: {{ .Values.api.name }}
  ports:
    - port: {{ .Values.api.service.grpcPort }}
      targetPort: {{ .Values.api.container.grpcPort }}
