{{- if eq .Values.mode "saas" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.director.name }}-configmap
  labels:
    {{- include "governor.selectorLabels" . | nindent 4 }}
data:
{{- if .Values.director.container.config }}
{{ toYaml .Values.director.container.config | indent 2}}
{{- end }}
{{- end }}
