{{- range .Values.databases }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}-custom-scripts
  labels:
    app: {{ $.Chart.Name }}
data:
{{- if and .configMap .configMap.customScripts }}
{{- range $filename, $content := .configMap.customScripts }}
  {{ $filename }}: |
{{ $content | indent 4 }}
{{- end }}
{{- else }}
  dummy.sql: |
    -- No custom scripts provided
{{- end }}
---
{{- end }}
