apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-custom-scripts
  labels:
    app: {{ .Chart.Name }}
data:
{{- if .Values.configMap.customScripts }}
{{- range $filename, $content := .Values.configMap.customScripts }}
  {{ $filename }}: |
{{ $content | indent 4 }}
{{- end }}
{{- else }}
  dummy.sql: |
    -- No custom scripts provided
{{- end }}

  {{- if .Values.configMap.env }}
  {{- range $key, $value := .Values.configMap.env }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
  {{- else }}
  debug-env: "No environment variables defined"
  {{- end }}
