{{- range .Values.databases }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-postgres-secret
  labels:
    app: {{ $.Chart.Name }}
type: Opaque
data:
  POSTGRES_USER: {{ .secret.postgresUser | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .secret.postgresPassword | default (randAlphaNum (int .secret.postgresPasswordLength)) | b64enc | quote }}
---
{{- end }}
