apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
  labels:
    app: {{ .Chart.Name }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secret.postgresUser | b64enc | quote }}
  POSTGRES_PASSWORD: {{ randAlphaNum (int .Values.secret.postgresPasswordLength) | b64enc | quote }}
