apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pagila
  labels:
    app: {{ .Chart.Name }}
spec:
  clusterIP: None
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
  selector:
    app: {{ .Chart.Name }}
