{{- range .Values.databases }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    app: {{ $.Chart.Name }}
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ .service.port }}
      targetPort: 5432
  selector:
    app: {{ $.Chart.Name }}-{{ .name }}
---
{{- end }}
