{{- range .Values.databases }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .name }}
  labels:
    app: {{ $.Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $.Chart.Name }}-{{ .name }}
  serviceName: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ $.Chart.Name }}-{{ .name }}
    spec:
      containers:
      - name: {{ .name }}
        image: "{{ .image.repository }}:{{ .image.tag }}"
        imagePullPolicy: {{ .image.pullPolicy }}
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .name }}-postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .name }}-postgres-secret
              key: POSTGRES_PASSWORD
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        {{- if and .configMap .configMap.customScripts }}
        - name: custom-scripts
          mountPath: /docker-entrypoint-initdb.d
        {{- end }}
        - name: data
          mountPath: /var/lib/postgresql/data
      volumes:
      {{- if and .configMap .configMap.customScripts }}
      - name: custom-scripts
        configMap:
          name: {{ .name }}-custom-scripts
      {{- end }}
  {{- if .ephemeral }}
      volumes:
      - name: data
        emptyDir: {}
  {{- else }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - {{ .persistence.accessMode }}
      resources:
        requests:
          storage: {{ .persistence.size }}
  {{- end }}
---
{{- end }}
