{{- with .Values.api.saml }}
{{- if and .enabled (not .signing.external) }}
{{ include "governor.certificate" (dict
  "root" $
  "name" (printf "%s-saml-signing" $.Values.api.name)
  "app" $.Values.api.name
  "secretName" .signing.keyPairSecret.name
  "cert" .signing.certManager
) }}
{{- end }}
{{- end }}
