{{- $w := include "governor.workerValues" . | fromYaml -}}
{{- if .Values.tlsInternal.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $w.name }}-envoy-config
  labels:
    app: {{ $w.name }}
    {{- include "governor.selectorLabels" . | nindent 4 }}
data:
  envoy.yaml: |
    {{- include "governor.envoy.node" (dict "componentName" $w.name "Release" .Release) | nindent 4 }}
    admin:
      address:
        socket_address:
          address: 0.0.0.0
          port_value: {{ .Values.tlsInternal.ports.admin }}

    static_resources:
      listeners:
        {{- include "governor.envoy.apiGrpcEgressListener" (dict "egressGrpcPort" .Values.tlsInternal.ports.egressGrpc) | nindent 8 }}

      clusters:
        {{- include "governor.envoy.apiGrpcsCluster" (dict "apiName" .Values.api.name "apiGrpcPort" .Values.api.service.grpcPort) | nindent 8 }}
  upstream_validation_context.yaml: |
    {{- include "governor.envoy.upstreamValidationContextSdsSecret" . | nindent 4 }}
{{- end }}
