
{{- if .Values.agent.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.agent.persistence.claimName }}
  labels:
    app: {{ .Values.agent.name }}
    {{- include "governor.selectorLabels" . | nindent 4 }}
spec:
  {{- if .Values.agent.persistence.storageClassName }}
  storageClassName: {{ .Values.agent.persistence.storageClassName }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.agent.persistence.size }}
{{- end }}
