apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.agent.name }}-secret
type: Opaque
data:
{{- range $k, $v := .Values.agent.container.secretConfig }}
  {{ $k }}: {{ $v | b64enc | quote }}
{{- end }}
