apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.front.name }}-secret
type: Opaque
data:
{{- range $k, $v := .Values.front.container.secretConfig }}
  {{ $k }}: {{ $v | b64enc | quote }}
{{- end }}
