mode: hybrid-cloud
sandbox: false
openshiftEnabled: false

aurora:
  enabled: true
  masterUsername: governor_admin
  secretNamespace: default
  secretName: db-secret
  secretKey: password
  dbSubnetGroupName: tenants-production-aurora-subnet-group
  securityGroupIds:
    - sg-0f3ec8186664db851
  backupRetentionPeriod: 7
  instanceClass: db.r6g.large
  serverless:
    minCapacity: 0
    maxCapacity: 4
    autoPauseSeconds: 300

api:
  name: governor-api
  group: governor-api
  image:
    repository: synthesizedio/synthesized-api
    tag: latest
    pullPolicy: Always
  securityContext:
    runAsUser: 100
    fsGroup: 65533
  container:
    port: 8081
    grpcPort: 50055
    config:
      SPRING_PROFILES_ACTIVE: production
      VERSION: 'not-specified'
      UI_ENVIRONMENT: "hybrid-cloud"
    # Sensitive configuration variables that will be rendered as a new secret
    secretConfig:
      ADMIN_EMAIL: "admin@synthesized.io"
  persistence:
    enabled: false
    name: api-pv
    mountPath: /data
    claimName: api-pvc
    size: 10Gi
  service:
    type: ClusterIP
    port: 80
    grpcPort: 50055

front:
  name: governor-front
  group: governor-front
  image:
    repository: synthesizedio/synthesized-front
    tag: latest
    pullPolicy: Always
  container:
    port: 8080
    config:
      # private hosts
      API_INTERNAL_HOST: 'governor-api'
      API_GRPC_INTERNAL_PORT: '50055'
      API_HTTP_INTERNAL_PORT: '80'
      UI_TDK_AGENTS: "true"
      UI_TDK_AGENTS_BY_DEFAULT: "true"
      UI_PII_SCAN: "true"
      UI_WORKFLOW_WIZARD: "true"
      UI_ENVIRONMENT: "hybrid-cloud"
    secretConfig:
      POSTHOG_ANALYTICS_API_KEY: ""
  service:
    type: ClusterIP
    port: 80

agent:
  name: governor-agent
  group: governor-director
  image:
    repository: synthesizedio/synthesized-agent
    tag: latest
    pullPolicy: Always
  container:
    config:
      AGENT_SERVERHOST: 'governor-api'
      AGENT_SERVERPORT: '50055'
      AGENT_TAGS: 'default'
      AGENT_DATASOURCES: '*'
      AGENT_USEPLAINTEXT: "true"
      AGENT_CONNECTIONS_POOL_SIZE: '20'

director:
  name: governor-director
  group: governor-director
  image:
    repository: synthesized.azurecr.io/synthesized-director
    tag: latest
    pullPolicy: Always
  container:
    port: 50051
    config:
      OPENAI_API_VERSION: "2023-03-15-preview"
      AZURE_DEPLOYMENT: "gpt-35-turbo"
      AZURE_OPENAI_ENDPOINT: "https://director-openai.openai.azure.com/"
    secretConfig:
      AZURE_OPENAI_API_KEY: ""
      DATABASE_URL_POSTGRES: ""
    command:
      - python3.9
      - director/server.py
    healthchecks:
  service:
    type: ClusterIP
    port: 50051

nodeSelector: {}

tolerations: []

affinity: {}

ingress:
  enabled: false

grpcIngress:
  enabled: false
