mode: self-hosted
sandbox: false
openshiftEnabled: false

aurora:
  enabled: true
  masterUsername: admin
  secretNamespace: default
  secretName: db-secret
  secretKey: password
  dbSubnetGroupName: default
  securityGroupIds:
    - sg-fcc8e897
  backupRetentionPeriod: 7
  instanceClass: db.r6g.large

api:
  name: governor-api
  group: governor-api
  image:
    repository: synthesizedio/synthesized-api
    pullPolicy: Always
  securityContext:
    runAsUser: 100
    fsGroup: 65533
  container:
    port: 8081
    grpcPort: 50055
    config:
      SPRING_PROFILES_ACTIVE: production
      VERSION: 'not-specified'
    # Sensitive configuration variables that will be rendered as a new secret
    secretConfig:
      SPRING_DATASOURCE_URL: ""
      SPRING_DATASOURCE_USERNAME: ""
      SPRING_DATASOURCE_PASSWORD: ""
      JWT_SECRET: ""
      ADMIN_EMAIL: ""
      ADMIN_DEFAULT_PASSWORD: ""
  persistence:
    enabled: false
    name: api-pv
    mountPath: /data
    claimName: api-pvc
    size: 10Gi
  service:
    type: ClusterIP
    port: 80
    grpcPort: 50055

front:
  name: governor-front
  group: governor-front
  image:
    repository: synthesizedio/synthesized-front
    pullPolicy: Always
  container:
    port: 8080
    config:
      # private hosts
      API_INTERNAL_HOST: 'governor-api'
      API_GRPC_INTERNAL_PORT: '50055'
      API_HTTP_INTERNAL_PORT: '80'
      UI_TDK_AGENTS: "true"
      UI_TDK_AGENTS_BY_DEFAULT: "true"
      UI_PII_SCAN: "true"
      UI_WORKFLOW_WIZARD: "true"
    secretConfig:
      POSTHOG_ANALYTICS_API_KEY: ""
  service:
    type: ClusterIP
    port: 80

agent:
  name: governor-agent
  group: governor-director
  image:
    repository: synthesizedio/synthesized-agent
    pullPolicy: Always
  container:
    config:
      AGENT_SERVERHOST: 'governor-api'
      AGENT_SERVERPORT: '50055'
      AGENT_TAGS: 'default'
      AGENT_DATASOURCES: '*'
      AGENT_USEPLAINTEXT: "true"
      AGENT_CONNECTIONS_POOL_SIZE: '20'

director:
  name: governor-director
  group: governor-director
  image:
    repository: synthesized.azurecr.io/synthesized-director
    pullPolicy: Always
  container:
    port: 50051
    config:
      OPENAI_API_VERSION: "2023-03-15-preview"
      AZURE_DEPLOYMENT: "gpt-35-turbo"
      AZURE_OPENAI_ENDPOINT: "https://director-openai.openai.azure.com/"
    secretConfig:
      AZURE_OPENAI_API_KEY: ""
      DATABASE_URL_POSTGRES: ""
    command:
      - python3.9
      - director/server.py
    healthchecks:
  service:
    type: ClusterIP
    port: 50051

nodeSelector: {}

tolerations: []

affinity: {}

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: webapprouting.kubernetes.azure.com
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: example.synthesized.io
      paths:
        - path: /
          service: governor-front
          servicePort: 80
        - path: /api
          service: governor-api
          servicePort: 8081
  tls:
    - secretName: tls-secret
      hosts:
        - example.synthesized.io

grpcIngress:
  enabled: false
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    kubernetes.io/ingress.class: webapprouting.kubernetes.azure.com
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: grpc.example.synthesized.io
      paths:
        - path: /api
          service: governor-api
          servicePort: 50055
  tls:
    - secretName: grpc-tls-secret
      hosts:
        - grpc.example.synthesized.io
