name: Static verification

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  static-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          pip install yamllint

      - name: Verify yamls
        run: |
          yamllint -s .

      - name: Verify Helm charts
        run: |
          helm lint charts/tdk
          helm lint charts/sdk
          helm lint charts/governor
