name: Helm Chart Package and Push to Artifactory

on:
  repository_dispatch:
    types:
      - helm-chart-push

jobs:
  helm:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./charts

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: Azure/setup-helm@v4.2.0
        with:
          version: v3.11.0
        id: install

      - name: Extract Image Tag and Chart Version from Dispatch Event
        id: extract_tags
        run: |
          echo "IMAGE_TAG=${{ github.event.client_payload.image_tag }}" >> $GITHUB_ENV
          echo "CHART_VERSION=${{ github.event.client_payload.chart_version }}" >> $GITHUB_ENV
          echo "CHART_NAME=${{ github.event.client_payload.chart_name }}" >> $GITHUB_ENV

      - name: Package Helm chart with Image Tag
        run: |
          helm package ${{ env.CHART_NAME }} --version ${{ env.CHART_VERSION }} --app-version ${{ env.IMAGE_TAG }}

      # - name: Install JFrog cli
      #   uses: jfrog/setup-jfrog-cli@v4.0.2
      #   env:
      #     JF_URL: ${{ vars.ARTIFACTORY_URL }}
      #     JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}

      - name: Helm login && push to oci jfrog artifactory registry
        run: |
          helm registry login ${{ vars.ARTIFACTORY_URL }} -p ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
          helm push ${{ env.CHART_NAME }}-${{ env.CHART_VERSION}}.tgz ${{ vars.ARTIFACTORY_URL }}/helm

      # - name: Push Helm Chart to Artifactory
      #   run: |
      #     jf rt u ${{ env.CHART_NAME }}-${{ env.CHART_VERSION}}.tgz helm/${{ env.CHART_NAME }}/${{ env.CHART_NAME }}-${{ env.CHART_VERSION}}.tgz
