name: Helm Chart Package and Push to Artifactory

on:
  repository_dispatch:
    types:
      - helm-chart-push

jobs:
  helm:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./charts

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.0

      - name: Extract Image Tag and Chart Version from Dispatch Event
        id: extract_tags
        run: |
          echo "IMAGE_TAG=${{ github.event.client_payload.image_tag }}" >> $GITHUB_ENV
          echo "CHART_VERSION=${{ github.event.client_payload.chart_version }}" >> $GITHUB_ENV
          echo "CHART_NAME=${{ github.event.client_payload.chart_name }}" >> $GITHUB_ENV

      - name: Package Helm chart with Image Tag
        run: |
          helm package ${{ env.CHART_NAME }} --version ${{ env.CHART_VERSION }} --app-version ${{ env.IMAGE_TAG }}

      - name: Push Helm Chart to Artifactory
        run: |
          CHART_PACKAGE=$(ls ./${{ env.CHART_NAME }}-*.tgz | head -n1)
          ARTIFACTORY_REPO="${{ env.ARTIFACTORY_URL }}/helm/${{ env.CHART_NAME }}"
          curl -X PUT "$ARTIFACTORY_REPO" \
            -H "Authorization: Bearer ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}" \
            -T "$CHART_PACKAGE"
        env:
          ARTIFACTORY_URL: ${{ vars.ARTIFACTORY_URL }}  # Using environment variable here
          ARTIFACTORY_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
